### ISSUE TITLE
Incompatible with TB 3.2 

### ISSUE THREAD

**Issue by provoke** [torquebox/backstage#36]
Undefined method join for String

**Comment by tobias** [comment]
Do you have a stack trace? What version of JRuby are you using - the bundled one or your own?

**Comment by provoke** [comment]
Standard bundled JRuby. Stack attached.
[server.log.txt](https://github.com/torquebox/backstage/files/586593/server.log.txt)

**Comment by tobias** [comment]
The real issue is the first exception: `NameError - missing class name (`org.Torquebox')`. This is coming from [code in jmx](https://github.com/enebo/jmx/blob/master/lib/jmx/mbeans.rb#L22) that creates modules to represent the remote java class, and it is finding a constant `Org` that points to the `JavaPackage` for `org`, but I'm not sure where that is getting defined - I can't find it in TorqueBox or Backstage. 

But, I think the reason `jmx` is finding that `Org` constant is changes in the way ruby looks up constants, maybe. If so, the real fix is to get `jmx` to do the right thing. I'm working on a PR for it now.

**Comment by tobias** [comment]
This should be fixed in Backstage 1.1.2.
